name: rwet
channels:
  - conda-forge
dependencies:
  - python
  - tensorflow
  - pandas
  - matplotlib
  - spacy
  - pip:
    - markovify
    - annoy==1.16.3
    - simpleneighbors
    - pronouncing
    - tracery
    - textgenrnn
